.TH pacstrap-container 1  "May 29, 2015" "Version 0.3" "USER COMMANDS"
.SH NAME
pacstrap-container \- arch-linux systemd containers
.SH SYNOPSIS
.B pacstrap-container (create|delete) [OPTIONS] NAME
 Description:
  (COMMANDS):
        create          create a new container
        delete          delete a container

  [OPTIONS]:
        create
                -b      enable container startup on boot
                -q      no output
        delete
                -q      no output

  NAME:
    systemd container/machine name
.SH DESCRIPTION
Simple way to create arch-linux systemd containers.
.SH EXIT STATUS
(0) Success.
(90) Error: Machine name already exists.
(91) Usage Error.
(all other) represents the passed through return value of a called executable.
.SH LICENSE
MIT-License
.SH AUTHOR
Antonino Catinello (ac (at) antoo.org)
